
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Exponer el puerto 80 de nginx en el puerto 8081 de tu host otro cambio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Solo si tienes un archivo nginx.conf personalizado
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
